services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www/app
        volumes:
            - ../.:/var/www/app
        networks:
            - app_network
        ports:
            - "9030:9010"

    webserver:
        image: nginx:latest
        container_name: app_webserver
        ports:
            - "9090:9090"
        volumes:
            - .:/var/www/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app_network

    db:
        image: mysql:8.0
        container_name: app_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    dbdata:
